spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/learning_management_system}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      password: admin
      name: admin
