spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/arcone}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
